### ISSUE TITLE
Working on design 

### ISSUE THREAD

**Issue by jdorvilier** [BloodDonate/BloodDonation#3]
Please clone the project and working on the design. I would like you to do a Sliding Tabs with 3 tabs named Reservation, Donation and Regulations.

**Comment by rodneyp079** [comment]
Ok, i receive your message in spam. 













OCS/VAS Engineer at NATCOM S.A.Tel : +509 4283-8678/3788-6399E-mail : petitrodney@yahoo.fr/rodneyp@natcom.com.htWhatsapp: +509 4283-8678Facebook : Petit-frere RodneyTwitter : frere_rodneyGitHub: https://github.com/rodneyp079 

    Le Mercredi 23 août 2017 13h43, Jonathan Dorvilier <notifications@github.com> a écrit :
 

 Please clone the project and working on the design. I would like you to do a Sliding Tabs with 3 tabs named Reservation, Donation and Regulations.—
